<header>
    <nav class="page-header-nav">
        <a href="index.php?">Home</a>
        <?php
        if (isset($_SESSION['email'])) {
        ?>

            <a href="index.php?route=users">Users</a>
            <a href="index.php?route=categories">Categories</a>
            <a href="index.php?route=deconnexion">Deconnexion</a>
        <?php
        } else {
        ?>
            <a href="index.php?route=connexion">Connexion</a>
            <a href="index.php?route=inscription">Inscription</a>
        <?php
        }
        ?>
    </nav>
</header>