<main>
    <h1>Inscription</h1>
    <form action="index.php?route=check-inscription" method="post">

        <label for="username">Username</label>
        <input type="text" name="username" id="username" required>
        <label for="email">Email</label>
        <input type="email" name="email" id="email" required>
        <label for="password">Password</label>
        <input type="password" name="password" id="password" required>
        <label for="role">role</label>
        <input type="text" name="role" id="role" required>
        <label for="createdAt">Created at</label>
        <input type="datetime-local" name="createdAt" id="createdAt" required>
        <button type="submit">Add new User</button>
    </form>
</main>