<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="utf-8" />
    <title>BLOG MVC</title>
</head>

<body>

    <?php
    require 'templates/header.phtml';
    if ($route === "home") {
        require 'templates/home.phtml';
    } else if ($route === "connexion") {
        require 'templates/connexion.phtml';
    } else if ($route === "inscription") {
        require 'templates/inscription.phtml';
    } else if ($route === "categories") {
        require 'templates/categories.phtml';
    } else if ($route === "category") {
        require 'templates/category.phtml';
    } else if ($route === "post") {
        require 'templates/post.phtml';
    } else if ($route === "error") {
        require 'templates/error.phtml';
    } else if ($route === "users") {
        require 'templates/users.phtml';
    } else {
        require 'templates/404.phtml';
    }
    ?>
</body>

</html>