<article>
    <h2> <?= $post->getTitle() ?> </h2>
    <p>Written by <?php
                    $userManager = new UserManager;
                    $author = $userManager->findOneById($post->getAuthor());
                    echo $author->getUsername();

                    ?> - Date : <?= $post->getCreatedAt() ?> </p>
    <p> <?= $post->getExcerpt() ?> </p>
    <p><?= $post->getContent() ?></p>
</article>