<h2>Users</h2>
<?php
if (isset($_SESSION['email'])) {

    if (isset($_GET['updateUser'])) {
        $userToUpdate = $instance->findOneById($_GET['updateUser']);
        $date = substr_replace($userToUpdate->getCreatedAt(), 'T', 10, 1);

?>
        <form action="index.php?route=updateUser&user=<?= $_GET['updateUser'] ?>" method="post">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" value=<?= $userToUpdate->getUsername() ?> required>
            <label for="email">Email</label>
            <input type="email" name="email" id="email" value=<?= $userToUpdate->getEmail() ?> required>
            <label for="password">Password</label>
            <input type="password" name="password" id="password" value=<?= $userToUpdate->getPassword() ?> required>
            <label for="role">role</label>
            <input type="text" name="role" id="role" value=<?= $userToUpdate->getRole() ?> required>
            <label for="createdAt">Created at</label>
            <input type="datetime-local" name="createdAt" id="createdAt" value=<?= $date ?> required>
            <button type="submit">Update User</button>
        </form>
    <?php
    } else {
    ?>
        <form action="index.php?route=createUser" method="post">
            <label for="username">Username</label>
            <input type="text" name="username" id="username" required>
            <label for="email">Email</label>
            <input type="email" name="email" id="email" required>
            <label for="password">Password</label>
            <input type="password" name="password" id="password" required>
            <label for="role">role</label>
            <input type="text" name="role" id="role" required>
            <label for="createdAt">Created at</label>
            <input type="datetime-local" name="createdAt" id="createdAt" required>
            <button type="submit">Add new User</button>
        </form>

    <?php
    } ?>
    <table class="col my-5 table table-striped">
        <thead>
            <tr>
                <th>
                    #
                </th>
                <th>
                    Nom d'utilisateur
                </th>
                <th>
                    Email
                </th>
                <th>
                    Mot de passe
                </th>
                <th>
                    Rôle
                </th>
                <th>
                    Date de création
                </th>
                <th>
                    Supprimer
                </th>
            </tr>
        </thead>
        <tbody>
            <?php
            $userManager = new UserManager;
            $users = $userManager->findAll();
            foreach ($users as $user) {
            ?>
                <tr>
                    <td> <?= $user['id'] ?> </td>
                    <td> <?= $user['username'] ?> </td>
                    <td> <?= $user['email'] ?> </td>
                    <td> <?= $user['password'] ?> </td>
                    <td> <?= $user['role'] ?> </td>
                    <td> <?= $user['created_at'] ?> </td>

                    <td>
                        <a href="index.php?route=users&updateUser=<?= $user['id'] ?>">
                            Modify user
                        </a>
                        <a href="index.php?route=deleteUser&user=<?= $user['id'] ?>">
                            Delete user
                        </a>
                    </td>
                </tr>
            <?php
            };
            ?>
        </tbody>
        <tfoot>
            <tr>
                <th>
                    #
                </th>
                <th>
                    Nom d'utilisateur
                </th>
                <th>
                    Email
                </th>
                <th>
                    Mot de passe
                </th>
                <th>
                    Rôle
                </th>
                <th>
                    Date de création
                </th>
                <th>
                    Supprimer
                </th>
            </tr>
        </tfoot>
    </table>

<?php
} else {

    echo "Vous n'avez pas les bases";
} ?>