<main>
    <div class="intro-banner">
        <h1>Tout sur la League</h1>
        <p>Les joueurs, les équipes et l'actu des matchs</p>
    </div>


    <?php
    $teamManager = new TeamManager();
    $playerManager = new PlayerManager();
    $highlightTeam = $teamManager->getRandomTeam();
    $highlightTeamMedia = $teamManager->getMedia($highlightTeam->getId())
    ?>
    <article class="article-equipe">
        <h2 class="yellow-text">L'équipe à la une</h2>
        <div class="team-info">
            <h3 class="yellow-text"><?= $highlightTeam->getName() ?></h3>
            <img src="<?= $highlightTeamMedia->getUrl() ?>" alt="<?= $highlightTeamMedia->getAlt() ?>" />
        </div>
        <div class="team-players">
            <p>Les joueurs</p>
            <div class="team-player-box">
                <?php
                $teammates = $playerManager->getTeammates($highlightTeam->getId());
                foreach ($teammates as $teammate) {
                    $media = $playerManager->getMedia($teammate->getId());
                ?>
                    <div class="team-player-card">

                        <img src="<?= $media->getUrl() ?>" alt="<?= $media->getAlt() ?>" />
                        <p class="player-name"><?= $teammate->getNickname() ?></p>

                    </div>
                <?php
                }
                ?>

            </div>
        </div>
    </article>
    <article class="article-players">
        <h2>Les joueurs à la une</h2>
        <div class="player-box">
            <div class="player-card">
                <img src="https://maridoucet.sites.3wa.io/league/players/Dundy.png" alt="" />
                <p class="player-name">Dundy</p>
                <p class="team-name yellow-text">Perroquets Bavards</p>
            </div>
            <div class="player-card">
                <img src="https://maridoucet.sites.3wa.io/league/players/Wofin.png" alt="" />
                <p class="player-name">Wofin</p>
                <p class="team-name yellow-text">Panthères</p>
            </div>
            <div class="player-card">
                <img src="https://maridoucet.sites.3wa.io/league/players/Stonk.png" alt="" />
                <p class="player-name">Stonks</p>
                <p class="team-name yellow-text">Moineau</p>
            </div>
        </div>
    </article>
    <article class="article-match">
        <h2>Le dernier match</h2>

        <div class="match-images">
            <img src="https://maridoucet.sites.3wa.io/league/teams/vendetta.png" alt="Logo Vendetta" />
            <div class="match-infos">
                <h3>Vendetta - Owls</h3>
                <p>17/01/2024</p>
            </div>
            <img src="https://maridoucet.sites.3wa.io/league/teams/angry-owls.png" alt="Logo Angry Owls" />
        </div>
    </article>
</main>