<main>
    <div class="intro-banner">
        <h1>Tout sur la League</h1>
        <p>Les joueurs, les équipes et l'actu des matchs</p>
    </div>


    <?php
    $teamManager = new TeamManager();
    $playerManager = new PlayerManager();
    $highlightTeam = $teamManager->getRandomTeam();
    $highlightTeamMedia = $teamManager->getMedia($highlightTeam->getId())
    ?>
    <article class="article-equipe">
        <h2 class="yellow-text">L'équipe à la une</h2>
        <div class="team-info">
            <h3 class="yellow-text"><?= $highlightTeam->getName() ?></h3>
            <img src="<?= $highlightTeamMedia->getUrl() ?>" alt="<?= $highlightTeamMedia->getAlt() ?>" />
        </div>
        <div class="team-players">
            <p>Les joueurs</p>
            <div class="team-player-box">
                <?php
                $teammates = $playerManager->getTeammates($highlightTeam->getId());
                foreach ($teammates as $teammate) {
                    $media = $playerManager->getMedia($teammate->getId());
                ?>
                    <div class="team-player-card">

                        <img src="<?= $media->getUrl() ?>" alt="<?= $media->getAlt() ?>" />
                        <p class="player-name"><?= $teammate->getNickname() ?></p>

                    </div>
                <?php
                }
                ?>

            </div>
        </div>
    </article>
    <article class="article-players">
        <h2>Les joueurs à la une</h2>
        <div class="player-box">
            <?php
            $highlightPlayers = $playerManager->get3RandomPlayers();

            foreach ($highlightPlayers as $player) {
                $media = $playerManager->getMedia($player->getId());
                $team = $playerManager->getTeam($player->getId())
            ?>
                <div class="player-card">
                    <img src="<?= $media->getUrl() ?>" alt="<?= $media->getAlt() ?>" />
                    <p class="player-name"><?= $player->getNickname() ?></p>
                    <p class="team-name yellow-text"><?= $team->getName() ?></p>
                    <a class="player-link-button pink-text" href="index.php?route=player&player=<?= $player->getId() ?>">Découvrez <?= $player->getNickname() ?></a>
                </div>
            <?php
            }
            ?>
        </div>
    </article>
    <article class="article-match">
        <h2>Le dernier match</h2>

        <div class="match-images">
            <img src="https://maridoucet.sites.3wa.io/league/teams/vendetta.png" alt="Logo Vendetta" />
            <div class="match-infos">
                <h3>Vendetta - Owls</h3>
                <p>17/01/2024</p>
            </div>
            <img src="https://maridoucet.sites.3wa.io/league/teams/angry-owls.png" alt="Logo Angry Owls" />
        </div>
    </article>
</main>