<main id="home" class="py-5 px-3">
    <h1 class="mb-5"> <?= $this->translator->translate("site_title") ?>
    </h1>

    <h2 class="mt-5"> <?= $this->translator->translate("latest_title") ?>
    </h2>
    <ul class="row mt-5">
        <?php
        foreach ($data["posts"] as $post) {
        ?>
            <li class="col-4 my-2">
                <article class="card">
                    <header class="card-body">
                        <h3 class="h5 card-title"><?= $post->getTitle() ?></h3>
                        <h4 class="h6 card-subtitle mb-2 text-body-secondary">
                            <?php
                            foreach ($post->getCategories() as $category) {
                                var_dump($category);
                                echo "{$category["title"]} ";
                            }
                            ?>
                        </h4>
                    </header>
                    <section class="card-body">
                        <p class="card-text"><?= $post->getExcerpt() ?></p>
                        <a href="index.php?route=post&post_id=<?= $post->getId() ?>" class="btn btn-primary"> <?= $this->translator->translate("post_link") ?>
                        </a>
                    </section>
                </article>
            </li>
        <?php
        }
        ?>
    </ul>
</main>